### ISSUE TITLE
Uport credentials with private chain

### ISSUE THREAD

**Issue by sandramarianegeorge** [uport-project/uport-credentials#143]
Use uport-credentials to issue private chain based credentials to support private chain provisioning flow

**Comment by rmw2** [comment]
Hi @sandramarianegeorge -- 

A credential in the verifiable claims sense is not associated with a particular chain, but with a DID (i.e., an identity).  The DID method that we are currently supporting is called `EthrDID`, and also is chain-agnostic, in that it only requires a keypair, and no on-chain transactions.  We do use a version of the ethr-did-registry contract deployed on mainnet to handle keypair changes and signing delegates, but the actual identity itself is indicated by possession of the keypair.  As the point of a did registry is to be public (so that changes to the keypair controlling a DID can be looked up by anyone interacting with that DID), we do not have plans to support deployment of the ethr-did-registry on private chains.

It is still very possible to verify and process signed claims on a private chain, and a keypair corresponding to a DID can be used as an address on a private ethereum network, while the identity registry remains on mainnet.

Feel free to reply if you have more questions!

**Comment by sandramarianegeorge** [comment]
Hi,
So can you update uport-credentials library to include the private provisioning method ?

**Comment by rogargon** [comment]
Please, I would also appreciate a small code sample showing the recommended way to get a keypair and use it on a private Ethereum network.
